### ISSUE TITLE
Could DiyOS fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [leonardoms/DiyOS#10]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

@leonardoms , If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

I see that the current ISO of DiyOS weights just 2.1MB, which is quite close to 1.44MB. It could be possible to borrow a slimmer build of grub bootloader from Fiwix - https://www.fiwix.org/downloads.html

**Comment by leonardoms** [comment]
Hi,
About the 2.1MB size, in RamDisk has uncompressed images, so we can easily take 1.44MB or less on a build.

About CoreBoot, thats a nice project, but my actual MB (GIGABYTE B360M) is not suported by that :(

If you want to try, i suggest a Fork and i can help you to adapt the DiyOS to run over BIOS chip!

thanks.

**Comment by informer2016** [comment]
Sadly the latest Intel boards supported by coreboot are Ivy Bridge _(and could try to use coreboot's "autoport" utility to port to the not-supported-yet board)_. Then, starting with Haswell, Intel has added the Boot Guard anti-feature, which prevents the booting of unsigned BIOS images, so - unless the motherboard manufacturer wants it (like Purism) - coreboot couldn't happen for such boards.

By the way, there is also Intel ME (Management Engine) hardware backdoor at all the Intel boards later than Pentium 4. At Core 2 Duo it's possible to completely remove ME firmware, but for the later boards - even coreboot-supported - could remove only a part of that firmware, hoping it loses the ability to spy after that. ME could have a complete access to your RAM / HDD / etc., stealing your top secret stuff over the networking adapter. Btw its' firmware is based on Minix, so Minix is the most popular OS in the world :stuck_out_tongue: 

AMD also has its' alternative backdoor - AMD PSP _(Platform Secure Processor)_ - but they introduced it much later than Intel made their ME, so the latest-AMD-without-PSP is much more powerful than Intel-without-ME. And almost all the coreboot supported AMD boards don't have such a backdoor _(with the exception of some PC Engines networking boards)_. If you are interested, I could suggest Lenovo G505S laptop with quadcore AMD A10-5750M CPU, and there are also interesting desktop/server boards...

Please tell, maybe you have some older laptops/motherboards, that are either coreboot-supported or maybe could become supported with this "autoport" utility and some minor work? My programming skills are quite limited and perhaps not enough for a DiyOS fork (I'm mostly a user / bug reporter), so I just hope that if I could help you with coreboot then a floppy version of DiyOS would be a direct benefit for you :wink:
