### ISSUE TITLE
How to run on real hardware

### ISSUE THREAD

**Issue by dimutch833** [leonardoms/DiyOS#11]
Please give information about booting DiyOs on Real hardware

**Comment by leonardoms** [comment]
if you use Linux, just copy the kernel (DiyOS_x86) and ramdisk (bin/ramdisk.tar) to the your system /boot dir, then add a entry for the DiyOS kernel on grub menu.lst config file, like this:

```
title	diyOS (x86)
root	(hd0,0)  # this depend of your /boot location
kernel	/DiyOS_x86
module  /ramdisk.tar
boot
```
