### ISSUE TITLE
Bug on start

### ISSUE THREAD

**Issue by dimutch833** [leonardoms/DiyOS#13]
(https://user-images.githubusercontent.com/48991276/83122358-31625a80-a0dc-11ea-9c3c-5be28cf75197.png)

**Comment by dimutch833** [comment]
What can i do

**Comment by yeppiidev** [comment]
Same issue with me. Try rebuilding from source and then run it.

**Comment by asiawin** [comment]
Same issue with me. Try rebuilding from source and then run it.
