### ISSUE TITLE
Mouse bug in QEMU for Windows and Ubuntu

### ISSUE THREAD

**Issue by yeppiidev** [leonardoms/DiyOS#14]
The mouse pointer is showing, but moving in an irregular way. It is out of control. Bug both when starting DiyOS in QEMU for Windows and Ubuntu. Please resolve this issue.

**Comment by leonardoms** [comment]
Thanks for reporting, its a know bug (on some versions  of virtual machines) and are on my priority. The system need a more responsive mouse driver.

**Comment by yeppiidev** [comment]
Thanks, @leonardoms
